function Interfata() 
Fig=figure('Name','Proprietati',...            
    'Units','normalized',...             
    'Position',[0.1 0.15 0.42 0.45],...           
    'NumberTitle','off','color',[0, 0.4, 0.71]); 

c=imread('prop.jpg');
subplot('Position',[0.2 0.01 0.6 0.45]);
imshow(c);
d=imread('lm.png');
subplot('Position',[0.03 0.5 0.45 0.45]);
imshow(d);
k=imread('7411.png');
subplot('Position',[0.51 0.5 0.45 0.45]);
imshow(k);
Bt=uicontrol('Style','text',...             
    'Units','normalized',...              
    'Position',[0.08 0.95 0.35 0.04],... 
    'backgroundcolor','white',... 
    'foregroundcolor','black',...             
    'String','Amplificator Operational in format DIL'); 

Bt_1=uicontrol('Style','text',...             
    'Units','normalized',...              
    'Position',[0.566 0.95 0.35 0.04],... 
    'backgroundcolor','white',... 
    'foregroundcolor','black',...             
    'String','Diagrama Blocului Intern'); 

Bt_2=uicontrol('Style','text',...             
    'Units','normalized',...              
    'Position',[0.327 0.45 0.35 0.04],...  
    'backgroundcolor','white',... 
    'foregroundcolor','black',...             
    'String','Parametrii Tehnici');
