function Proiect_interfata(A,f,N,E,W,R1,R2,sss)   
Fig=figure('Name','Comparator cu AO',...      %%%%%%figura      
    'Units','normalized',...             
    'Position',[0.1 0.1 0.73 0.61],...           
    'NumberTitle','off','color',[0, 0.4, 0.71]); 

%%%%parametri de intrare
T=1/f;
t=0:T/100:5*T;
vi=A.*sin(2.*pi.*f.*t);  


%butoane
%%%%%%%%%%%%%%%%%%%%%%%%%%%Proprietati
Bp=uicontrol('Style','pushbutton',...              
    'Units','normalized',...             
    'Position',[0.49 0.92 0.17 0.05],...   
    'BackgroundColor','white',...
    'String','Proprietati Amplficator',...             
    'Callback','Interfata();'); 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%parametri semnal de intrare
                 RadioGroup=uibuttongroup('Visible','on',...                          
                     'BackgroundColor','white',...                          
                     'ForegroundColor','black',...                          
                     'Title','Parametri semnalului intrare/iesire',...                          
                     'FontSize',11,...                          
                     'TitlePosition','centertop',...                          
                     'Tag','radiobutton',...                          
                     'Position',[0.789 0.6 0.21 0.26]);



            uicontrol('Style','text',...           
                'Units','normalized',...           
                'Position',[0.08 0.72 0.4 0.15],...            
                'backgroundcolor','white',...               
                'foregroundcolor','red',...           
                'String','f [Hz]',...
                'Parent',RadioGroup);
            Be=uicontrol('Style','edit',...              
                'Units','normalized',...              
                'Position',[0.5 0.72 0.4 0.12],...              
                'foregroundcolor','b',...              
                'String',f,...              
                'Callback','f=str2num(get(gco,''string'')),close,Proiect_interfata(A,f,N,E,W,R1,R2,sss);',...
            'Parent',RadioGroup);
        
   uicontrol('Style','text',...           
                'Units','normalized',...           
                'Position',[0.08 0.52 0.4 0.15],...            
                'backgroundcolor','white',...               
                'foregroundcolor','red',...           
                'String','A [V]',...
                'Parent',RadioGroup);
            Be=uicontrol('Style','edit',...              
                'Units','normalized',...              
                'Position',[0.5 0.52 0.4 0.12],...              
                'foregroundcolor','b',...              
                'String',A,...              
                'Callback','A=str2num(get(gco,''string'')),close,Proiect_interfata(A,f,N,E,W,R1,R2,sss);',...
            'Parent',RadioGroup);
        
  uicontrol('Style','text',...           
                'Units','normalized',...           
                'Position',[0.08 0.32 0.4 0.15],...            
                'backgroundcolor','white',...               
                'foregroundcolor','red',...           
                'String','+E[V] ',...
                'Parent',RadioGroup);
            
            Be=uicontrol('Style','edit',...              
                'Units','normalized',...              
                'Position',[0.5 0.32 0.4 0.12],...              
                'foregroundcolor','b',...              
                'String',E,...              
                'Callback','E=str2num(get(gco,''string'')),close,Proiect_interfata(A,f,N,E,W,R1,R2,sss);',...
                'Parent',RadioGroup);
            
        uicontrol('Style','text',...           
                'Units','normalized',...           
                'Position',[0.08 0.12 0.4 0.15],...            
                'backgroundcolor','white',...               
                'foregroundcolor','red',...           
                'String','-E[V] ',...
                'Parent',RadioGroup);
            
            Be=uicontrol('Style','edit',...              
                'Units','normalized',...              
                'Position',[0.5 0.12 0.4 0.12],...              
                'foregroundcolor','b',...              
                'String',W,...              
                'Callback','W=str2num(get(gco,''string'')),close,Proiect_interfata(A,f,N,E,W,R1,R2,sss);',...
                'Parent',RadioGroup);
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%praguri
         RadioGroup1=uibuttongroup('Visible','on',...                          
                     'BackgroundColor','white',...                          
                     'ForegroundColor','black',...                          
                     'Title','Tensiunele de Prag',...                          
                     'FontSize',11,...                          
                     'TitlePosition','centertop',...                          
                     'Tag','radiobutton',...                          
                     'Position',[0.4 0.6 0.2 0.26]);
                 
                 BAtext=uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.48 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'Vps [V]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',RadioGroup1);
            
            BTtext=uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.72 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'Vpj [V]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',RadioGroup1);
               
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%end praguri

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% popup
            
Bp_u=uicontrol('Style','PopupMenu',...                
    'Units','normalized',...                
    'Position',[0.73 0.86 0.2 0.1],... 
    'value',sss,...
    'String','Comparator Inversor|Comparator Neinversor',...                
    'Callback','sss=get(gco,''value''),close;Proiect_interfata(A,f,N,E,W,R1,R2,sss)'); 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%rezistente

RadioGroup2=uibuttongroup('Visible','on',...
                     'BackgroundColor','white',...
                     'ForegroundColor','black',...
                     'Title','Rezistentile',...
                     'FontSize',11,...
                     'TitlePosition','centertop',...
                     'Position',[0.59 0.6 0.2 0.26]);

BT=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.72 0.4 0.15],...
            'String', R1,...
            'Tag','R1',...
            'Callback','R1=str2num(get(gco,''string'')),close,Proiect_interfata(A,f,N,E,W,R1,R2,sss)',...
            'Parent',RadioGroup2);
BTtext=uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.72 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'R1 [Ohm]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',RadioGroup2);
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
            
            
BA=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.48 0.4 0.15],...
            'String', R2,...
            'Tag','R2',...
            'Callback','R2=str2num(get(gco,''string'')),close,Proiect_interfata(A,f,N,E,W,R1,R2,sss)',...
            'Parent',RadioGroup2);
BAtext=uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.48 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'R2 [Ohm]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',RadioGroup2);
            
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% grafice

switch sss
    case 1

[X2,map2]=imread('inversor1.png');%inversor
subplot('Position',[0.07 0.6 0.32 0.35]); 
imshow(X2,map2);                        

n=length(t);
Vps=R1/(R2)*E;
Vpj=R1/(R2)*W;

Vp1=-Vps;
Vp=Vps;
for i=1:n
    if vi(i)>Vp
        vo(i)=-E;
        Vp=Vp1;
    elseif vi(i)<Vp
        vo(i)=E;
        Vp=Vps;
    end
 end
   
subplot('Position',[0.07 0.13 0.43 0.34]);
% subplot(2,2,3);
plot(t,vi,'r'); 
hold on;
grid on;
subplot('Position',[0.07 0.13 0.43 0.34]);
plot(t,vo,'b');
hold on; 
grid on;
title('Tensiunea intrare/iesire a comparatorului');
xlabel('timp [s]');         
ylabel('Amplitudine [V]'); 
legend('Vi','Vo');


%%%%%%%%%%%%%%prag
BT=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.72 0.4 0.15],...
            'String', Vps,...
            'Callback','',...
            'Parent',RadioGroup1);

            BA=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.48 0.4 0.15],...
            'String', Vpj,...
            'Callback','',...
            'Parent',RadioGroup1);
%%%%%%%%%%%%%%%%%%%%%%%%
    case 2
[X1,map1]=imread('neinversor.png');
subplot('Position',[0.07 0.6 0.32 0.35]); 
imshow(X1,map1);
n=length(t);
Vps1=R1/(R2+R1)*E;
Vpj1=R1/(R2+R1)*W;


 
Vp1=-Vps1;
Vp=Vps1;
for i=1:n
    if vi(i)>Vp
        vo(i)=E;
        Vp=Vp1;
    elseif vi(i)<Vp
        vo(i)=-E;
        Vp=Vps1;
    end
    
end
 
BT=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.72 0.4 0.15],...
            'String', Vps1,...
            'Callback','',...
            'Parent',RadioGroup1);

            BA=uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.48 0.4 0.15],...
            'String', Vpj1,...
            'Callback','',...
            'Parent',RadioGroup1);
 
   
subplot('Position',[0.07 0.13 0.43 0.34]);
plot(t,vi,'r'); 
hold on;
grid on;
subplot('Position',[0.07 0.13 0.43 0.34]);
plot(t,vo,'b');
hold on; 
grid on;
title('Tensiunea intrare/iesire a comparatorului');
xlabel('timp [s]');         
ylabel('Amplitudine [V]'); 
legend('Vi','Vo');

end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fct=uimenu('Label','Documentatie','Separator','on');   
 uimenu(fct,'Label','Autor','Callback','Autor()');           
 uimenu(fct,'Label','Bibliografie','Callback','Bibliografie()'); 
 uimenu(fct,'Label','Teorie','Callback','Teorie()');
 
 %%%%%%%%%%%%%histereza
 subplot('Position',[0.54 0.13 0.43 0.34]);
     cla;
    plot(vi,vo,'g');
    hold on; 
    grid on;
    title('Caracteristica Vo-Vi');
    xlabel('Vi [V]');
    ylabel('Vo [V]');
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%% error
    msg = 'Valoarea tensiunii de alimentare trebuie sa fie cuprinsa intre 5 si 40 V';
if E>40
    error(msg);   
end

    msg = 'Valoarea tensiunii de alimentare trebuie sa fie cuprinsa intre 5 si 40 V';
if E<5
    error(msg);  
end

    msg = 'Valoarea tensiunii de alimentare trebuie sa fie cuprinsa intre 5 si 40 V';
if W<-40
    error(msg);  
end

    msg = 'Valoarea tensiunii de alimentare trebuie sa fie cuprinsa intre 5 si 40 V';
if W>-5
    error(msg);  
    
end
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 



